### ISSUE TITLE
Slow performance on Android

### ISSUE THREAD

**Issue by sanketsahusoft** [shoutem/theme#13] opened 2017-03-07 07:12 UTC
First of all! A huge thanks for this repo. I was going to build my own styling engine and then I stumbled upon this repo.

I am Sanket from the NativeBase team and with the latest version of NativeBase 2.0 we have used `shoutem/theme` as the core styling engine for our components.

We have realized that the performance on Android is really slow on complex pages and the bottleneck lies in the `resolveComponentStyle` file where the actual merge happens. Any solution for that?

**Comment by tenodi** [comment] 2017-03-07 07:32
Hi, @sanketsahusoft! Thanks a lot for submitting this issue. We are thrilled that NativeBase is using `shoutem/theme` as the core styling engine! Can you provide us with some examples?

**Comment by sanketsahusoft** [comment] 2017-03-07 08:06
Thanks for the quick reply @tenodi!

You can check the KitchenSink app on Exponent here: https://exp.host/@shivrajkumar/nativebase-kitchenSink

Goto `Menu > List > List Icon` on an Android phone. It takes upto 1-2 second to open up the page.

The source code for that component is hosted here: https://github.com/GeekyAnts/NativeBase-KitchenSink/blob/master/js/components/list/list-icon.js

**Comment by MrBr** [comment] 2017-03-07 09:17
Hi @sanketsahusoft,

Just trying to get a better picture here, have some questions.

How did you realize that `resolveComponentStyle` is bottleneck? How did you get the metrics and can you provide the data?

Also what I would appreciate if you could confirm number of expected renders vs actual for this specific case. Basically I want to confirm that component is not rendered more times then needed. I guess if you are just visiting for this screen once there should be only one render of that component.

I have take a quick look at `NativeBase` and what concerns me is that you have `mapPropsToStyleNames` on every component. We have `styleName` property for that , that is how we planned to use specific component variants. We introduced `mapPropsToStyleNames` as edge case function, where you can change `styleName` depending on props, it it should not be abused.

What concerns me here the most is that I am not certain how does it affect application if you have `mapPropsToStyleNames` on every component. I am not sure if it affects performance in significant  way but it definitively activates additional comparison.

From the code itself I am not able to conclude if there is something wrong.

**Comment by himanshu-satija** [comment] 2017-03-07 11:35
Hi @MrBr, I am Himanshu from NativeBase team.

We are testing the performance on the screen which Sanket has mentioned `Menu > List > List Icon`. I can confirm that the component is only rendered once. As there are 11 list items on that page, component 'LIstItem' form NativeBase is being rendered 11 times.

We can see that `resolveComponentStyle` is being called for each component which means that it will be called for all the `ListItem`s and their children and grandchildren. For this specific screen, `resolveComponentStyle` is being called 111 times.

As for the metrics, I have listed below the time difference (in milliseconds) between `componentWillMount` and `componentDidMount` for the same screen in various cases (debugging OFF):

-  Plain React Native with StyleSheet.create ~ **840**
- NativeBase 2.0
  - Using shoutem/theme as it is with `mapPropsToStyleNames` ~ **2200**
  - Using shoutem/theme as it is without `mapPropsToStyleNames` ~ **2100**
  - Return WrappedComponent in the first line of function `wrapWithStyledComponent` avoiding all the operations inside `connectStyle` ~ **950**
  - Execute `connectSyle` fully but return empty objects from `resolveComponentStyle` avoiding merge operations (including `mapPropsToStyleNames`) ~ **1350**

**Comment by MrBr** [comment] 2017-03-07 13:52
All right, thank you for the information.

I have to think a little bit about the whole situation and consult with colleagues.

Will come back with some feedback.

Just one note, inline style should be avoided, especially when passing plain object like `style={{...style}}`. This way you are always passing new reference which will trigger additional style calculation and also changes props unnecessary.

**Comment by sanketsahusoft** [comment] 2017-03-08 04:57
@MrBr Makes sense!

Meanwhile, we are also working on optimizations. One route which we have taken is to pre-process all the merges so that it is skipped during execution.

**Comment by wcandillon** [comment] 2017-05-15 06:23
@sanketsahusoft @MrBr I was investigating slow performances on my nativebase 2.0 app and also realized that shoutem/theme was the bottle neck. I was happy to see that you guys are already on the case! Looking forward to see processes on this and I will investigate it on my side as well.

**Comment by sanketsahusoft** [comment] 2017-05-16 08:06
Hi William,

We have solved the performance issue with NativeBase 2.1.0. It's just that
_.merge() is not very performant and we have replaced that with recursive
loops.

Best,
Sanket

**Comment by Vladimir-Vdovic** [comment] 2017-09-13 07:02
Issue seems to be resolved, closing it. Please prompt for reopen if issue is still relevant.

**Closed by Vladimir-Vdovic** 2017-09-13 07:02 UTC
Labels: question
