### ISSUE TITLE
There is some error with react-native@0.45

### ISSUE THREAD

**Issue by iwlog** [shoutem/theme#23] opened 2017-06-21 08:25 UTC
There is some error with react-native@0.45

**Comment by Vladimir-Vdovic** [comment] 2017-06-21 08:30
The current workaround (until we update the UI toolkit) is to set up dependencies for your project (and reinstall node modules) as described by user dobrienlzd: 

https://github.com/shoutem/ui/issues/241#issuecomment-298602614.

Going to mark this issue as a duplicate of https://github.com/shoutem/ui/issues/241.

Please reference mentioned issue for future updates.

**Closed by Vladimir-Vdovic** 2017-06-21 08:30 UTC
